export default {
  "__environment__": "pro",
  "RSDX_API": "https://lbzg.api.rsdx.com",
  "YUNSHANG_API": "https://app.yunshang520.com",
  "PROXY_MALL_API": "https://mall.kang-boss.com/proxy/mall-api",
  "BASE_API": "https://steamengine-api.kang-boss.com",
  "COMMISSION_BASE_URL": "https://lbb-gw.tojoycloud.com",
  "VITE_BUCKET": "steamengine-1314672876",
  "VITE_REGION": "ap-nanjing",
  "VITE_DOMAIN": "https://resource.kang-boss.com",
  "VITE_PROTOCOL": "https://resource.kang-boss.com",
  "KBOSS_WEB_API": "https://mall.kang-boss.com",
  "SDK_API": "https://platform-api.kang-boss.com",
  "IM_SDK_APPID": 1600026865,
  "APP_ID": "10012",
  "APP_KEY": "9W5AYZ78",
  "APP_SECRET": "078af4ee71012d4d724e394b65049816977c7520",
  "ACCOUNT_ID": "100000",
  "SENSORS_DATA_URL": "https://shence.tojoyshare.com:8443/sa?project=production",
  "FACE_DETECT_API": "https://api.utours.cn/open-service/face-detect/redirect-h5"
}